# Generated by Django 3.0.8 on 2021-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('output_format', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'geolocation',
            },
        ),
    ]
